kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client
rules:
- apiGroups: [""]
  resources: ["services", "pods", "configmaps", "endpoints", "secrets"]
  verbs: ["get", "watch", "list"]